let cafes = [
  {
    id: 'cafe-1',
    title: 'Mélanger Les Space ',
    image: '/images/melanger.png',
    location: 'Jl. H. Wasyid No.5, Bandung',
    foodprice: 'Rp 20.000 - Rp 30.000 / orang',
    drinkprice: 'Rp 20.000 - Rp 30.000 / orang',
    category: 'Cafe and Resto',
    reservasi: 'https://wa.me/6287737613008?text=Halo%20Melanger%20Les%20Space,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Minggu (09.00 - 23.00)',
    bayar: 'Cash, Visa, Master, Debet, Go-pay, Ovo, Dana',
    rasa: '4.4',
    kebersihan: '4.7',
    kenyamanan: '4.5',
    pelayanan: '4.5',
    ig: 'https://www.instagram.com/melanger___/?next=%2F&hl=id',
  },
  {
    id: 'cafe-2',
    title: 'Hanami Cafe & Sky Lounge ',
    image: '/images/Hanami-Cafe-Bandung.png',
    location: 'Jl. Cihampelas No. 254, Cihampelas, Bandung',
    drinkprice: 'Rp 6.000 - Rp 125.000 / orang',
    foodprice: 'Rp 12.000 - Rp 105.000 / orang',
    category: 'Cafe and Sky Lounge Resto',
    reservasi: 'https://wa.me/6287871010897?text=Halo%20Hanammi%20Cafe,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Jumat (12.00 - 20.30 WIB)',
    bayar: 'Cash, Visa, Master, Debet, Go-pay, Ovo',
    rasa: '3.9',
    kebersihan: '4.4',
    kenyamanan: '4.5',
    pelayanan: '4.4',
    ig: 'https://www.instagram.com/hanamiskylounge/?next=%2F&hl=id',
  },
  {
    id: 'cafe-3',
    title: 'The Soko Coffee ',
    image: '/images/thesoko.png',
    location: 'Jl. Resort Dago Pakar No. 19, Dago Atas, Bandung',
    drinkprice: 'Rp 15.000 - Rp 38.000 / item',
    foodprice: 'Rp 20.000 - Rp 60.000 / item',
    category: 'Cafe',
    reservasi: 'https://wa.me/6285156538920?text=Halo%20Soko%20Cafe,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Sabtu (10:00 - 23:00 WIB)',
    bayar: 'Cash, Debet, QRIS',
    rasa: '3.9',
    kebersihan: '4.5',
    kenyamanan: '4.2',
    pelayanan: '4.4',
    ig: 'https://www.instagram.com/thesokoctc/?next=%2F&hl=id',
  },

  {
    id: 'cafe-4',
    title: 'Simpang Wangi Coffee & Eatery ',
    image: '/images/simpangwangi.png',
    location: 'Jl. Hayam Wuruk No. 24, Gedung Sate, Bandung',
    drinkprice: 'Rp 20.000 - Rp 40.000 / item',
    foodprice: 'Rp 20.000 - Rp 72.000 / item',
    category: 'Cafe',
    reservasi: 'https://wa.me/628112424211text=Halo%20Simpang%20Wangi,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Minggu (07.00 - 22.00 WIB)',
    bayar: 'Cash, Debet, QRIS',
    rasa: '4.2',
    kebersihan: '4.5',
    kenyamanan: '4.4',
    pelayanan: '4.3',
    ig: 'https://www.instagram.com/simpangwangi/?next=%2F&hl=id',
  },
  {
    id: 'cafe-5',
    title: 'Upnormal Coffee Roasters  ',
    image: '/images/upnormal.png',
    location: 'Jl. L.L.R.E. Martadinata No. 158',
    drinkprice: 'Rp 8.000 - Rp 27.000 / item',
    foodprice: 'Rp 10.000 - Rp 40.000 / item',
    category: 'Cafe',
    reservasi: 'https://wa.me/628112102821?text=Halo%20Upnormal%20Coffe,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Minggu (09:00 - 22:00 WIB)',
    bayar: 'Cash, Debet, QRIS',
    rasa: '4.6',
    kebersihan: '4.5',
    kenyamanan: '4.7',
    pelayanan: '4.5',
    ig: 'https://www.instagram.com/upnormalcoffeeroasters/?next=%2F&hl=id',
  },
  {
    id: 'cafe-6',
    title: 'Rockmen and Coffee  ',
    image: '/images/rockmen.png',
    location: 'Jl. Ciliwung No. 17, Riau, Bandung',
    drinkprice: 'Rp 18.000 - Rp 37.000 / orang',
    foodprice: 'Rp 18.000 - Rp 45.000 / orang',
    category: 'Cafe',
    reservasi: 'https://wa.me/628112384900?text=Halo%20Rockmen%20Cafe,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Minggu (07:00 - 21:00 WIB)',
    bayar: 'Cash, Debet, QRIS',
    rasa: '4.5',
    kebersihan: '4.7',
    kenyamanan: '4.8',
    pelayanan: '4.2',
    ig: 'https://www.instagram.com/rockmenandcoffee/?next=%2F&hl=id',
  },
  {
    id: 'cafe-7',
    title: 'Wip Koffie ',
    image: '/images/wip.png',
    location: 'Jl. Hasanudin No. 28, Dipatiukur, Bandung',
    drinkprice: 'Rp 15.000 - Rp 55.000 / item',
    foodprice: 'Rp 25.000 - Rp 69.000 / item',
    category: 'Cafe and Eatery',
    reservasi: 'https://wa.me/62817347774?text=Halo%20Wip%20Koffie,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Minggu (09:00 - 22:00 WIB)',
    bayar: 'Cash, Debet, QRIS',
    rasa: '4.4',
    kebersihan: '4.5',
    kenyamanan: '4.7',
    pelayanan: '4.6',
    ig: 'https://www.instagram.com/wip.koffie/?next=%2F&hl=id',
  },
  {
    id: 'cafe-8',
    title: 'Serantau Coffee & Space   ',
    image: '/images/serantau.png',
    location: 'Jl. Nanas No. 13, Riau, Bandung',
    drinkprice: 'Rp 20.000 - Rp 30.000 / orang',
    foodprice: 'Rp 10.000 - Rp 35.000 / orang',
    category: 'Cafe',
    reservasi: 'https://wa.me/628123844299?text=Halo%20Serantau%20Cafe,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Minggu (12:00 - 21:00 WIB)',
    bayar: 'Cash, Debet, QRIS',
    rasa: '3.9',
    kebersihan: '4.4',
    kenyamanan: '4.5',
    pelayanan: '4.5',
    ig: 'https://www.instagram.com/serantaucoffeespace/?next=%2F&hl=id',
  },
  {
    id: 'cafe-9',
    title: 'Delapan Padi',
    image: '/images/delapanpadi.png',
    location: 'Jl. Dipati Ukur No. 8, Dipatiukur, Bandung',
    drinkprice: 'Rp 7.000 - Rp 35.000 / orang',
    foodprice: 'Rp 30.000 - Rp 85.000 / orang',
    category: 'Cafe',
    reservasi: 'https://wa.me/628112099988?text=Halo%20Delapan%20Padi,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Jumat (08.00 - 22.00 WIB)',
    bayar: 'Cash, Visa, Master, Debet, Go-pay, Ovo, Dana',
    rasa: '4.0',
    kebersihan: '4.7',
    kenyamanan: '4.5',
    pelayanan: '4.4',
    ig: 'https://www.instagram.com/delapanpadi/?next=%2F&hl=id',
  },
  {
    id: 'cafe-10',
    title: 'Brewspace Coffee & Creative Space ',
    image: '/images/brewspace.png',
    location: 'Jl. Prabu Dimuntur No. 22, Dago Bawah, Bandung',
    drinkprice: 'Rp 16.000 - Rp 40.000 / orang',
    foodprice: 'Rp 13.000 - Rp 67.000 / orang',
    category: 'Cafe adn Working Space',
    reservasi: 'https://wa.me/6282111941292?text=Halo%20Brewspace,%20saya%20ingin%20menanyakan%20terkait%20reservasi',
    time: 'Senin - Minggu (08:00 - 23:00 WIB)',
    bayar: 'Cash, Debet, QRIS',
    rasa: '3.9',
    kebersihan: '4.4',
    kenyamanan: '4.3',
    pelayanan: '4.2',
    ig: 'https://www.instagram.com/brewspace.id/?hl=id',
  },
];

function getAllCafes() {
  return cafes;
}

function getCafe(id) {
  const foundedCafe = cafes.find((cafe) => cafe.id === id);
  return foundedCafe;
}

export { getAllCafes, getCafe };
